openapi: 3.0.3
info:
  title: linkpark
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/v1/auth/register:
    post:
      summary: ''
      operationId: postApiV1AuthRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Authorization and Authentication'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: katelynn.schmitt@example.org
                password:
                  type: string
                  description: ''
                  example: doloremque
                school_id:
                  type: integer
                  description: ''
                  example: 3
                user_type:
                  type: string
                  description: 'Must be one of <code>guardian</code> or <code>student</code>.'
                  example: student
                first_name:
                  type: string
                  description: ''
                  example: sint
                last_name:
                  type: string
                  description: ''
                  example: minus
              required:
                - email
                - password
                - school_id
                - user_type
                - first_name
                - last_name
      security: []
  /api/v1/auth/login:
    post:
      summary: ''
      operationId: postApiV1AuthLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Authorization and Authentication'
      security: []
  /api/v1/school:
    get:
      summary: ''
      operationId: getApiV1School
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 1
                      name: 'Jeramy Rowe'
                      created_at: '2023-04-12T00:36:13.000000Z'
                      updated_at: '2023-04-12T00:36:13.000000Z'
                    -
                      id: 2
                      name: 'Mr. Diamond Koss DDS'
                      created_at: '2023-04-12T00:36:13.000000Z'
                      updated_at: '2023-04-12T00:36:13.000000Z'
                    -
                      id: 3
                      name: 'Model secondary school'
                      created_at: '2023-04-12T00:36:41.000000Z'
                      updated_at: '2023-04-12T00:36:41.000000Z'
                  links:
                    first: 'http://localhost/api/v1/school?page=1'
                    last: 'http://localhost/api/v1/school?page=1'
                    prev: null
                    next: null
                  meta:
                    current_page: 1
                    from: 1
                    last_page: 1
                    links:
                      -
                        url: null
                        label: '&laquo; Previous'
                        active: false
                      -
                        url: 'http://localhost/api/v1/school?page=1'
                        label: '1'
                        active: true
                      -
                        url: null
                        label: 'Next &raquo;'
                        active: false
                    path: 'http://localhost/api/v1/school'
                    per_page: 10
                    to: 3
                    total: 3
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        name: 'Jeramy Rowe'
                        created_at: '2023-04-12T00:36:13.000000Z'
                        updated_at: '2023-04-12T00:36:13.000000Z'
                      -
                        id: 2
                        name: 'Mr. Diamond Koss DDS'
                        created_at: '2023-04-12T00:36:13.000000Z'
                        updated_at: '2023-04-12T00:36:13.000000Z'
                      -
                        id: 3
                        name: 'Model secondary school'
                        created_at: '2023-04-12T00:36:41.000000Z'
                        updated_at: '2023-04-12T00:36:41.000000Z'
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: 'Jeramy Rowe'
                        created_at:
                          type: string
                          example: '2023-04-12T00:36:13.000000Z'
                        updated_at:
                          type: string
                          example: '2023-04-12T00:36:13.000000Z'
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                        example: 'http://localhost/api/v1/school?page=1'
                      last:
                        type: string
                        example: 'http://localhost/api/v1/school?page=1'
                      prev:
                        type: string
                        example: null
                      next:
                        type: string
                        example: null
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 1
                      from:
                        type: integer
                        example: 1
                      last_page:
                        type: integer
                        example: 1
                      links:
                        type: array
                        example:
                          -
                            url: null
                            label: '&laquo; Previous'
                            active: false
                          -
                            url: 'http://localhost/api/v1/school?page=1'
                            label: '1'
                            active: true
                          -
                            url: null
                            label: 'Next &raquo;'
                            active: false
                        items:
                          type: object
                          properties:
                            url:
                              type: string
                              example: null
                            label:
                              type: string
                              example: '&laquo; Previous'
                            active:
                              type: boolean
                              example: false
                      path:
                        type: string
                        example: 'http://localhost/api/v1/school'
                      per_page:
                        type: integer
                        example: 10
                      to:
                        type: integer
                        example: 3
                      total:
                        type: integer
                        example: 3
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiV1School
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/v1/school/{id}':
    get:
      summary: ''
      operationId: getApiV1SchoolId
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 1
                    name: 'Jeramy Rowe'
                    created_at: '2023-04-12T00:36:13.000000Z'
                    updated_at: '2023-04-12T00:36:13.000000Z'
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: 'Jeramy Rowe'
                      created_at:
                        type: string
                        example: '2023-04-12T00:36:13.000000Z'
                      updated_at:
                        type: string
                        example: '2023-04-12T00:36:13.000000Z'
      tags:
        - Endpoints
      security: []
    patch:
      summary: ''
      operationId: patchApiV1SchoolId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the school.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/v1/school/{school_id}':
    delete:
      summary: ''
      operationId: deleteApiV1SchoolSchool_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: school_id
        description: 'The ID of the school.'
        example: 1
        required: true
        schema:
          type: integer
tags:
  -
    name: 'Authorization and Authentication'
    description: "\nEndpoints to Authorize and Authenticate a user"
  -
    name: Endpoints
    description: ''
