# name: Laravel

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   Linkpark-server-deploy:

#     runs-on: self-hosted

#     strategy:
#       matrix:
#         node-version: [18.x]

#     steps:
#     - name: Check User
#       run: |
#         whoami
#     - name: 🚚 Get latest code
#       uses: actions/checkout@v3

#     - name: Install Dependencies
#       run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

#     - name: Copy .env if not exist
#       run: cp -rf /var/www/config/.env /var/www/server/_work/linkpark-backend-server/linkpark-backend-server/.env

#     - name: Config Clearing
#       run: php artisan config:clear

#     - name: Cache Clearing
#       run: php artisan cache:clear

#     - name: Generate App Key
#       run: php artisan key:generate

#     - name: Generate storage link
#       run: php artisan storage:link

#     - name: Directory Permissions
#       run: chmod -R 777 storage bootstrap/cache

#     - name: Setup PHP with PECL extension
#       uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
#       with:
#         php-version: '8.2'

name: Laravel

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Changed Repository
        uses: actions/checkout@master

      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install Composer Dependencies
        run: composer2 install --no-dev

      - name: Generate Autoload Files
        run: composer2 dump-autoload

      - name: Clear Route Cache
        run: php artisan route:clear

      - name: Clear Cache
        run: php artisan cache:clear

      - name: Clear Configuration Cache
        run: php artisan config:clear

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$SSH_PASSPHRASE" > ~/.ssh/passphrase
          chmod 600 ~/.ssh/passphrase
        env:
          SSH_SECRET: ${{ secrets.SSH_KEY }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}

      - name: Execute Remote SSH Commands to Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: "65002"
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /home/u623889396/domains/tobiolanitori.com/public_html/linkparkapi
            ./deploy.sh
